### PR TITLE
fix logo linting through manual recreation

### PR DESCRIPTION
**Pull request by mashehu**
using  
`nf-core create-logo pairgenomealign --width 600 --theme dark`
and
` nf-core create-logo pairgenomealign --width 600` in a github codespace, makes the linting happy (hopefully 🤞🏻)

### CODE REVIEW

**Comment by mashehu** [comment]
okay, I see the problem now: with https://github.com/oist/plessy_pairwiseGenomeComparison/commit/96d77543da14d7c4b94b909fd07584f94b164157 the logos in TEMPLATE are actually not the ones created during the test run (long story short, for the tests we run the create command and compare against that, not actually what is in the TEMPLATE branch (because we assume, the TEMPLATE branch just contains the content of a `create` command with a certain tools verwion, without any changes to it (error message is misleading there, sorry)). 
Solutions: Either revert the above commit and `run git checkout upstream/TEMPLATE -- assets/nf-core-pairgenomealign_logo_light.png` etc or in the TEMPLATE branch run the create commands above with the `--width 600` option (less preferred, because one shouldn't touch the TEMPLATE branch normally)

**Comment by charles-plessy** [comment]
Thanks @mashehu! I have replaced (`git push --force`) the TEMPLATE branch with a new one that was made by a fresh run of `nf-core create`. Then I ran the linting action but it failed again…

**Comment by mashehu** [comment]
did you run `nf-core create` locally? The problem is on which platform the `nf-core create` was run. for linting it runs on a github runner, so running it inside a GitHub codespace and not locally should have the same effect (but not 100% sure)?

**Comment by charles-plessy** [comment]
@mashehu I ran it on a local Linux system. I never used GitHub codespaces. I will give it a try and let you know the result.

**Comment by charles-plessy** [comment]
@mashehu We tried GitHub codespaces.  First, I ran the empty codespace template, installed `nf-core` with pip, ran `nf-core create`, and replaced the `TEMPLATE` branch with the resulting files.  The older branch is now called `TEMPLATE_broken`. A diff shows that the generated PNG files have a different checksum.  However, the GitHub action still failed. 

Then I figured out that if I run a "new" codespace cloning the `TEMPLATE` branch, it will setup a `nf-core` environment using the `.devcontainer` directory. I ran `nf-core create` again, and replaced again the `TEMPLATE` branch (the previous one being renamed `TEMPLATE_broken2`). The GitHub action failed again.  Interstingly, `TEMPLATE` and `TEMPLATE_broken` have identical contents.

So there is something that causes image generation vary in some contexts.  I looked at the GitHub action file and it sets the environment in a different way than `.devcontainer`.  In particular, python's versions are different. However, I am still new to the codespaces system, and do not know how to create a codespace that reproduces the GitHub runner of the GitHub action.  Do you have something to suggest?

In any case, maybe these files could be just excluded from linting?

**Comment by charles-plessy** [comment]
FYI we are silencing the problem for the time being.  We can revisit it when the pipeline is ready. https://github.com/oist/plessy_pairwiseGenomeComparison/commit/eb36120ac4935d0f575cc439051bb27a79368962

**Comment by mashehu** [comment]
sorry, your message fell through labour-day. 🙂 yes, ignoring for now sounds good (we will hopefully have solved this until release 🙂)

**Comment by charles-plessy** [comment]
We now develop the pipeline in nf-core/pairgenomealign

**Pull request closed without merging**
